import moment from "moment";

const todayDate = moment(new Date()).format("yyyy-MM-DD");

const initialValuesBuildingApp = {
  landOwnershipStatus: "",
  landOwnershipMethod: "",
  addInfoworkScopeChecklist: [],
  landOwnershipForm: "",
  projLocProjectTitle: "",
  projLocLotNo: "",
  projLocBlkNo: "",
  projLocTctNo: "",
  projLocStreet: "",
  projLocBarangay: "",
  projLocTaxDecNo: "",
  projLocDisctrict: "",
  projLocCity: "",
  applicantSurname: "",
  applicantFirstname: "",
  applicantMI: "",
  applicantSuffix: "",
  applicantAddPurok: "",
  applicantAddSubdivision: "",
  applicantAddBarangay: "",
  applicantAddCity: "",
  applicantAddZipCode: "",
  applicantTel: "",
  authorizeSurname: "",
  authorizeFirstname: "",
  authorizeMIname: "",
  authorizeSuffix: "",
  authorizeAddPurok: "",
  authorizeAddSubdivision: "",
  authorizeAddBarangay: "",
  authorizeAddCity: "",
  authorizeAddZipCode: "",
  authorizeTel: "",
  AddInfoTypeActivity: "",
  addInfoInteriorUnitStallNumber: "",
  addInfoInteriorEstabName: "",
  addInfoInteriorStructWork: "",
  addInfoInteriorRenovationMall: "",
  addInfoInteriorLeasedSpace: "",
  addInfoInteriorBuildingNo: "",
  addInfoInteriorDate: todayDate,
  addInfoCharacterOccupancy: "",
  addInfoFollowUpQuestions: [],
  authorizedSwitch: false,
};

export { initialValuesBuildingApp };
