import moment from "moment";

const todayDate = moment(new Date()).format("yyyy-MM-DD");

const initialValuesBuildingApp = {
  landOwnershipStatus: "0",
  landOwnershipMethod: "0",
  landOwnershipForm: "0",
  projLocProjectTitle: "",
  projLocLotNo: "",
  projLocBlkNo: "",
  projLocTctNo: "",
  projLocStreet: "",
  projLocBarangay: "",
  projLocTaxDecNo: "",
  projLocDisctrict: "",
  projLocCity: "",
  applicantSurname: "",
  applicantFirstname: "",
  applicantMI: "",
  applicantSuffix: "",
  applicantAddPurok: "",
  applicantAddSubdivision: "",
  applicantAddBarangay: "",
  applicantAddCity: "",
  applicantAddZipCode: "",
  applicantTel: "",
  authorizedSwitch: false,
  authorizeSurname: "",
  authorizeFirstname: "",
  authorizeMIname: "",
  authorizeSuffix: "",
  authorizeAddPurok: "",
  authorizeAddSubdivision: "",
  authorizeAddBarangay: "",
  authorizeAddCity: "",
  authorizeAddZipCode: "",
  authorizeTel: "",
  AddInfoTypeActivity: "",
  addInfoworkScopeChecklist: [],
  addInfoInteriorUnitStallNumber: "",
  addInfoInteriorEstabName: "",
  addInfoInteriorStructWork: "",
  addInfoInteriorRenovationMall: "",
  addInfoInteriorLeasedSpace: "",
  addInfoInteriorBuildingNo: "",
  addInfoInteriorDate: todayDate,
  addInfoCharacterOccupancy: "",
  addInfoCharacterOccupancyFollowUp: "",
  addInfoFollowUpQuestions: [],
};

const questionsLabels = [
  "Ownership Status",
  "Method of lot/property acquisition",
  "Form of Ownership",
  "Project Title",
  "Lot No",
  "Blk No",
  "Tct No",
  "Street",
  "Barangay",
  "Tax dec No",
  "Disctrict",
  "City",
  "Surname",
  "First Name",
  "M.I",
  "Suffix",
  "Address",
  "Subdivision",
  "Barangay",
  "City",
  "Zip code",
  "Tel No",
  "Surname",
  "First Name",
  "M.I",
  "Has Authorized Person",
  "Suffix",
  "Address",
  "Subdivision",
  "Barangay",
  "City",
  "Zip code",
  "Tel No",
  "Type of Activity",
  "Work Scope",
  "Unit/ Stall Number",
  "Establisment Name",
  "Does the project involve any structural work?",
  "Is this an interior renovation within the mall?",
  "For Interior Renovation (Leased Space)",
  "Building Permit No.",
  "Date Issued",
  "Use of Character or Occupancy",
  "Follow Up Questions",
];

export { initialValuesBuildingApp, questionsLabels };
